package com.jobs.ags.hr.interviewprocess;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CandidateDetail implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String lob;
	private java.lang.String applicationId;

	private java.lang.String jobType;

	private java.lang.Boolean isGreApproved;

	private java.lang.String candidateId;

	private java.lang.String id;

	public CandidateDetail() {
	}

	public java.lang.String getLob() {
		return this.lob;
	}

	public void setLob(java.lang.String lob) {
		this.lob = lob;
	}

	public java.lang.String getApplicationId() {
		return this.applicationId;
	}

	public void setApplicationId(java.lang.String applicationId) {
		this.applicationId = applicationId;
	}

	public java.lang.String getJobType() {
		return this.jobType;
	}

	public void setJobType(java.lang.String jobType) {
		this.jobType = jobType;
	}

	public java.lang.Boolean getIsGreApproved() {
		return this.isGreApproved;
	}

	public void setIsGreApproved(java.lang.Boolean isGreApproved) {
		this.isGreApproved = isGreApproved;
	}

	public java.lang.String getCandidateId() {
		return this.candidateId;
	}

	public void setCandidateId(java.lang.String candidateId) {
		this.candidateId = candidateId;
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public CandidateDetail(java.lang.String lob,
			java.lang.String applicationId, java.lang.String jobType,
			java.lang.Boolean isGreApproved, java.lang.String candidateId,
			java.lang.String id) {
		this.lob = lob;
		this.applicationId = applicationId;
		this.jobType = jobType;
		this.isGreApproved = isGreApproved;
		this.candidateId = candidateId;
		this.id = id;
	}

}